type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Recipe @table {
  title: String!
  instructions: String!
  preparationTime: Int!
  servings: Int!
  isPublic: Boolean!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  category: String
  cuisine: String
  author: User
}

type MealPlan @table {
  name: String!
  planDate: Date!
  createdAt: Timestamp!
  description: String
  user: User
}

type MealPlanRecipe @table {
  dayOfWeek: String!
  mealType: String!
  notes: String
  mealPlan: MealPlan
  recipe: Recipe
}

type Review @table {
  rating: Int!
  createdAt: Timestamp!
  comment: String
  user: User
  recipe: Recipe
}

type RecipeIngredient @table {
  name: String!
  quantity: Float!
  unit: String!
  notes: String
  recipe: Recipe
}